# Generated by Django 5.0.3 on 2024-03-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тип(например мод)')),
                ('games', models.ManyToManyField(blank=True, default=None, related_name='types', to='home_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название файла')),
                ('about', models.CharField(max_length=250, verbose_name='О чем этот файл')),
                ('images', models.ImageField(blank=True, null=True, upload_to='files/images', verbose_name='Изображения')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('url', models.URLField(max_length=120, verbose_name='Ссылка для скачивания')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('favourite', models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='home_app.game')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='home_app.type')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
