# Generated by Django 5.0.3 on 2024-03-06 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='images',
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.CreateModel(
            name='FileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/images', verbose_name='Изображение')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home_app.file')),
            ],
            options={
                'verbose_name': 'Изображение файла',
                'verbose_name_plural': 'Изображении файла',
            },
        ),
    ]
