# Generated by Django 5.0.3 on 2024-03-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_type_options_squashed_0007_auto_20240306_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
