# Generated by Django 5.0.3 on 2024-03-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_fileimage_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='creator',
            new_name='author',
        ),
    ]
