# Generated by Django 5.0.3 on 2024-03-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_rename_creator_file_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='name',
        ),
    ]
