# Generated by Django 5.0.3 on 2024-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_rename_title_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='a', verbose_name='Slug'),
        ),
    ]
